version: '3.9'

services:
  db:
    image: mariadb:10.10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    deploy:
      replicas: 2

  web:
    image: nginx:alpine3.17
    restart: always

    ports:
      - target: 4003
        published: 4004
        protocol: tcp
        mode: host
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.labels.TAG==srv05"
